### ISSUE TITLE
Question about uploading image

### ISSUE THREAD

**Issue by CallMeL** [ECarry/photography-website-nextjs14-full-stack#2]
Hi there! Excuse me for taking your time again.
I tried to add photo record on [prisma](http://localhost:5555), but in the [home page](http://localhost:3000 ) it shows no data. 

<img width="1411" alt="Screenshot 2024-03-01 at 21 27 15" src="https://github.com/ECarry/photography-website-nextjs14-full-stack/assets/55145817/18d19875-397e-44e7-a58a-7e73951864b6">

<img width="353" alt="Screenshot 2024-03-01 at 21 27 29" src="https://github.com/ECarry/photography-website-nextjs14-full-stack/assets/55145817/ff0318bf-4f62-4a37-94f1-af3d7e254549">

I'm not sure whether the localhost:5555 is the right place to upload images, or there is another dashboard page for uploading, especially after we deploy the website using Vercel. 

Many thanks for your time and help!

**Comment by ECarry** [comment]
Hi there! I have fixed the issue you provided.

You need to perform the following steps: 
1. You should go to the `dev` dir and  perform a `git pull` to fetch the latest code to your local.
2. Regarding image uploading, you need to register an account on [UploadThing](https://uploadthing.com/dashboard) （free 2GB） and fill in the **API key** in the `.env` file. Then, back your site, log in to the` /dashboard`, go to the gallery to upload images.

If you are deploying on Vercel, you need to go to `Settings` and set up `Environment Variables`by providing the corresponding Key and Value. Make sure to set `NEXTAUTH_URL`to the deployment address on Vercel, rather than `http://localhost:3000/`.

**Comment by CallMeL** [comment]
@ECarry Thanks for the reply! 

In the `/dashboard` page, what is the password for it? I tried the password set in `http://localhost:5555`, but it says `Invalid credentials!`, should I set in the `.env` file?

Thanks again!

**Comment by ECarry** [comment]
**password**： Password use bcrypt hash, you can generate at https://bcrypt.online/ and Then copy the generated code to http://localhost:5555 **User** model password

Of course, you can set up the **username**, **password** and **email** in advance in the `.env` file. You can see the new additions 
```
# init user
USER_EMAIL = test@test.com
USERNAME = test
USER_PASSWORD = test
``` 
in the `.env.example` file, but you need to `git pull` the latest code first and go to http://localhost:5555 to delete your **old account**.

**Comment by CallMeL** [comment]
Thank you so much! It solved my problem perfectly!
